<?php

use App\Models\City;
use App\Models\BusStation;
use Illuminate\Database\Seeder;

class BusStationsTableSeeder extends Seeder
{
    protected $bus_stations = [
    ['name' => "Danubyu BS", 'number_of_gates' => 60, 'city_id' => 1, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hinthada BS", 'number_of_gates' => 60, 'city_id' => 2, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyonpyaw BS", 'number_of_gates' => 60, 'city_id' => 3, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pathein BS", 'number_of_gates' => 60, 'city_id' => 4, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Bago BS", 'number_of_gates' => 60, 'city_id' => 5, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Penwegon BS", 'number_of_gates' => 60, 'city_id' => 6, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nyaunglebin BS", 'number_of_gates' => 60, 'city_id' => 7, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Oktwin BS", 'number_of_gates' => 60, 'city_id' => 8, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kanyutkwin BS", 'number_of_gates' => 60, 'city_id' => 9, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Zayyawadi BS", 'number_of_gates' => 60, 'city_id' => 10, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Taungoo BS", 'number_of_gates' => 60, 'city_id' => 11, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thar Ga Ra BS", 'number_of_gates' => 60, 'city_id' => 12, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Waw BS", 'number_of_gates' => 60, 'city_id' => 13, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hswar BS", 'number_of_gates' => 60, 'city_id' => 14, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yae Ni BS", 'number_of_gates' => 60, 'city_id' => 15, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yedashe BS", 'number_of_gates' => 60, 'city_id' => 16, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Letpadan BS", 'number_of_gates' => 60, 'city_id' => 17, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Minhla(Bago) BS", 'number_of_gates' => 60, 'city_id' => 18, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nattalin BS", 'number_of_gates' => 60, 'city_id' => 19, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Oe Thei Kone BS", 'number_of_gates' => 60, 'city_id' => 20, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Paungde BS", 'number_of_gates' => 60, 'city_id' => 21, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyay BS", 'number_of_gates' => 60, 'city_id' => 22, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thonse BS", 'number_of_gates' => 60, 'city_id' => 23, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hpa-An BS", 'number_of_gates' => 60, 'city_id' => 24, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aunglan BS", 'number_of_gates' => 60, 'city_id' => 25, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Gangaw BS", 'number_of_gates' => 60, 'city_id' => 26, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Magway BS", 'number_of_gates' => 60, 'city_id' => 27, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kamma BS1", 'number_of_gates' => 60, 'city_id' => 28, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pakokku BS", 'number_of_gates' => 60, 'city_id' => 29, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pauk BS", 'number_of_gates' => 60, 'city_id' => 30, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Sinphyukyun BS", 'number_of_gates' => 60, 'city_id' => 31, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Taungdwingyi BS", 'number_of_gates' => 60, 'city_id' => 32, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myit Chay BS", 'number_of_gates' => 60, 'city_id' => 33, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yesagyo BS", 'number_of_gates' => 60, 'city_id' => 34, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thirimingalar BS", 'number_of_gates' => 60, 'city_id' => 35, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyigyimyatshin BS", 'number_of_gates' => 60, 'city_id' => 35, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Swetaw BS", 'number_of_gates' => 60, 'city_id' => 35, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaukpadaung BS", 'number_of_gates' => 60, 'city_id' => 36, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaukse BS", 'number_of_gates' => 60, 'city_id' => 37, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Meiktila BS", 'number_of_gates' => 60, 'city_id' => 38, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Myingyan BS", 'number_of_gates' => 60, 'city_id' => 39, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Natogyi BS", 'number_of_gates' => 60, 'city_id' => 40, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nyaung-U BS", 'number_of_gates' => 60, 'city_id' => 41, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyawbwe BS", 'number_of_gates' => 60, 'city_id' => 42, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyinoolwin BS", 'number_of_gates' => 60, 'city_id' => 43, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Taungtha BS", 'number_of_gates' => 60, 'city_id' => 44, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yamethin BS", 'number_of_gates' => 60, 'city_id' => 45, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Bilin BS", 'number_of_gates' => 60, 'city_id' => 46, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mawlamyine BS", 'number_of_gates' => 60, 'city_id' => 47, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lewe BS", 'number_of_gates' => 60, 'city_id' => 48, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Pyinmana BS", 'number_of_gates' => 60, 'city_id' => 49, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tatkon BS", 'number_of_gates' => 60, 'city_id' => 50, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nay Pyi Taw BS", 'number_of_gates' => 60, 'city_id' => 51, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thar Wut Hti BS", 'number_of_gates' => 60, 'city_id' => 52, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Chaung-U BS", 'number_of_gates' => 60, 'city_id' => 53, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kale BS", 'number_of_gates' => 60, 'city_id' => 54, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Khin-U BS", 'number_of_gates' => 60, 'city_id' => 55, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Monywa BS", 'number_of_gates' => 60, 'city_id' => 56, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myinmu BS", 'number_of_gates' => 60, 'city_id' => 57, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Sagaing BS", 'number_of_gates' => 60, 'city_id' => 58, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Shwebo BS", 'number_of_gates' => 60, 'city_id' => 59, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ye-U BS", 'number_of_gates' => 60, 'city_id' => 60, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kengtung BS", 'number_of_gates' => 60, 'city_id' => 61, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tachileik BS", 'number_of_gates' => 60, 'city_id' => 62, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aungpan BS", 'number_of_gates' => 60, 'city_id' => 63, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nyaungshwe BS", 'number_of_gates' => 60, 'city_id' => 64, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aye Thar Yar BS", 'number_of_gates' => 60, 'city_id' => 65, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Taunggyi BS", 'number_of_gates' => 60, 'city_id' => 65, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aung Mingalar BS-Online", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Dagon Aya BS-Online", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Parami BS-Online", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aung San Kwin BS-Online", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Elite Main Station BS-Online", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aung Mingalar BS-Regular", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Dagon Aya BS-Regular", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Parami BS-Regular", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aung San Kwin BS-Regular", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Elite Main Station BS-Regular", 'number_of_gates' => 60, 'city_id' => 66, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thanlyin BS", 'number_of_gates' => 60, 'city_id' => 67, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Sittwe BS", 'number_of_gates' => 60, 'city_id' => 68, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Bogale BS", 'number_of_gates' => 60, 'city_id' => 69, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Dedaye BS", 'number_of_gates' => 60, 'city_id' => 70, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Einme BS", 'number_of_gates' => 60, 'city_id' => 71, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Htoogyi BS", 'number_of_gates' => 60, 'city_id' => 72, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ingapu BS", 'number_of_gates' => 60, 'city_id' => 73, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kangyidaunt BS", 'number_of_gates' => 60, 'city_id' => 74, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaiklat BS", 'number_of_gates' => 60, 'city_id' => 75, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Batye BS", 'number_of_gates' => 60, 'city_id' => 76, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyangin BS", 'number_of_gates' => 60, 'city_id' => 77, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaunggon BS", 'number_of_gates' => 60, 'city_id' => 78, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Ahtaung BS", 'number_of_gates' => 60, 'city_id' => 79, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Labutta BS", 'number_of_gates' => 60, 'city_id' => 80, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "လပွတ္တာ (၃) မိုင် BS", 'number_of_gates' => 60, 'city_id' => 81, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyinsalu BS", 'number_of_gates' => 60, 'city_id' => 82, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lemyethna BS", 'number_of_gates' => 60, 'city_id' => 83, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Maubin BS", 'number_of_gates' => 60, 'city_id' => 84, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mawlamyinegyun BS", 'number_of_gates' => 60, 'city_id' => 85, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kanaung BS", 'number_of_gates' => 60, 'city_id' => 86, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myanaung BS", 'number_of_gates' => 60, 'city_id' => 87, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myaungmya BS", 'number_of_gates' => 60, 'city_id' => 88, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Hainggyikyun BS", 'number_of_gates' => 60, 'city_id' => 89, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ngapudaw BS", 'number_of_gates' => 60, 'city_id' => 90, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ngayokekaung BS", 'number_of_gates' => 60, 'city_id' => 91, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nyaungdon BS", 'number_of_gates' => 60, 'city_id' => 92, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pantanaw BS", 'number_of_gates' => 60, 'city_id' => 93, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ngwesaung BS", 'number_of_gates' => 60, 'city_id' => 94, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Shwethaungyan BS", 'number_of_gates' => 60, 'city_id' => 95, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ahmar BS", 'number_of_gates' => 60, 'city_id' => 96, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyapon BS", 'number_of_gates' => 60, 'city_id' => 97, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thabaung BS", 'number_of_gates' => 60, 'city_id' => 98, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Kyonmangae BS", 'number_of_gates' => 60, 'city_id' => 99, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Wakema BS", 'number_of_gates' => 60, 'city_id' => 100, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ahthoke BS", 'number_of_gates' => 60, 'city_id' => 101, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ngathaingchaung BS", 'number_of_gates' => 60, 'city_id' => 102, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yegyi BS", 'number_of_gates' => 60, 'city_id' => 103, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Zalun BS", 'number_of_gates' => 60, 'city_id' => 104, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hpayargyi BS", 'number_of_gates' => 60, 'city_id' => 105, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Inntakaw BS", 'number_of_gates' => 60, 'city_id' => 106, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Daik-U BS", 'number_of_gates' => 60, 'city_id' => 107, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Htantabin BS", 'number_of_gates' => 60, 'city_id' => 108, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Kawa BS", 'number_of_gates' => 60, 'city_id' => 109, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thetkala BS", 'number_of_gates' => 60, 'city_id' => 110, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaukkyi BS", 'number_of_gates' => 60, 'city_id' => 111, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyauktaga BS", 'number_of_gates' => 60, 'city_id' => 112, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Madauk BS", 'number_of_gates' => 60, 'city_id' => 113, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Peinzalok BS", 'number_of_gates' => 60, 'city_id' => 114, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyuntasa BS", 'number_of_gates' => 60, 'city_id' => 115, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Phyu BS", 'number_of_gates' => 60, 'city_id' => 116, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Shwegyin BS", 'number_of_gates' => 60, 'city_id' => 117, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kaytumati BS", 'number_of_gates' => 60, 'city_id' => 118, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Thanatpin BS", 'number_of_gates' => 60, 'city_id' => 119, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myo Hla BS 1", 'number_of_gates' => 60, 'city_id' => 120, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Gyobingauk BS", 'number_of_gates' => 60, 'city_id' => 121, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Monyo BS", 'number_of_gates' => 60, 'city_id' => 122, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Okpho BS", 'number_of_gates' => 60, 'city_id' => 123, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Oakshitpin BS", 'number_of_gates' => 60, 'city_id' => 124, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Padaung BS", 'number_of_gates' => 60, 'city_id' => 125, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Paukkhaung BS", 'number_of_gates' => 60, 'city_id' => 126, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Paungdale BS", 'number_of_gates' => 60, 'city_id' => 127, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Shwedaung BS", 'number_of_gates' => 60, 'city_id' => 128, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Thayarwady BS", 'number_of_gates' => 60, 'city_id' => 129, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Inn Ma BS", 'number_of_gates' => 60, 'city_id' => 130, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Puteekone BS", 'number_of_gates' => 60, 'city_id' => 131, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thegon BS", 'number_of_gates' => 60, 'city_id' => 132, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Zigon BS", 'number_of_gates' => 60, 'city_id' => 133, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Falam BS", 'number_of_gates' => 60, 'city_id' => 134, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Rihkhawdar BS", 'number_of_gates' => 60, 'city_id' => 135, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hakha BS", 'number_of_gates' => 60, 'city_id' => 136, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kanpetlet BS", 'number_of_gates' => 60, 'city_id' => 137, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Matupi BS", 'number_of_gates' => 60, 'city_id' => 138, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Rezua BS", 'number_of_gates' => 60, 'city_id' => 139, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mindat BS", 'number_of_gates' => 60, 'city_id' => 140, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Paletwa BS", 'number_of_gates' => 60, 'city_id' => 141, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Samee BS", 'number_of_gates' => 60, 'city_id' => 142, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tedim BS", 'number_of_gates' => 60, 'city_id' => 143, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thantlang BS", 'number_of_gates' => 60, 'city_id' => 144, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Cikha BS", 'number_of_gates' => 60, 'city_id' => 145, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tonzang BS", 'number_of_gates' => 60, 'city_id' => 146, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Bhamo BS", 'number_of_gates' => 60, 'city_id' => 147, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Chipwi BS", 'number_of_gates' => 60, 'city_id' => 148, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Pang War BS", 'number_of_gates' => 60, 'city_id' => 149, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hpakant BS", 'number_of_gates' => 60, 'city_id' => 150, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kamaing BS", 'number_of_gates' => 60, 'city_id' => 151, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Injangyang BS", 'number_of_gates' => 60, 'city_id' => 152, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Khaunglanhpu BS", 'number_of_gates' => 60, 'city_id' => 153, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Machanbaw BS", 'number_of_gates' => 60, 'city_id' => 154, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mansi BS", 'number_of_gates' => 60, 'city_id' => 155, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mogaung BS", 'number_of_gates' => 60, 'city_id' => 156, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nammatee BS", 'number_of_gates' => 60, 'city_id' => 157, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hopin BS", 'number_of_gates' => 60, 'city_id' => 158, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Mohnyin BS", 'number_of_gates' => 60, 'city_id' => 159, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Dawthponeyan BS", 'number_of_gates' => 60, 'city_id' => 160, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lwegel BS", 'number_of_gates' => 60, 'city_id' => 161, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Momauk BS", 'number_of_gates' => 60, 'city_id' => 162, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myitkyina BS", 'number_of_gates' => 60, 'city_id' => 163, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Sinbo BS", 'number_of_gates' => 60, 'city_id' => 164, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nawngmun BS", 'number_of_gates' => 60, 'city_id' => 165, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pannandin BS", 'number_of_gates' => 60, 'city_id' => 166, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Puta-O BS", 'number_of_gates' => 60, 'city_id' => 167, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myo Hla BS", 'number_of_gates' => 60, 'city_id' => 168, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Shwegu BS", 'number_of_gates' => 60, 'city_id' => 169, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Sumprabum BS", 'number_of_gates' => 60, 'city_id' => 170, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Shin Bway Yang BS", 'number_of_gates' => 60, 'city_id' => 171, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tanai BS", 'number_of_gates' => 60, 'city_id' => 172, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tsawlaw BS", 'number_of_gates' => 60, 'city_id' => 173, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kan Paik Ti BS", 'number_of_gates' => 60, 'city_id' => 174, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Sadung BS", 'number_of_gates' => 60, 'city_id' => 175, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Waingmaw BS", 'number_of_gates' => 60, 'city_id' => 176, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Bawlake BS", 'number_of_gates' => 60, 'city_id' => 177, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ywarthit BS", 'number_of_gates' => 60, 'city_id' => 178, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Demoso BS", 'number_of_gates' => 60, 'city_id' => 179, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hpasawng BS", 'number_of_gates' => 60, 'city_id' => 180, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hpruso BS", 'number_of_gates' => 60, 'city_id' => 181, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Loikaw BS", 'number_of_gates' => 60, 'city_id' => 182, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mese BS", 'number_of_gates' => 60, 'city_id' => 183, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Shadaw BS", 'number_of_gates' => 60, 'city_id' => 184, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hlaingbwe BS", 'number_of_gates' => 60, 'city_id' => 185, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Paingkyon BS", 'number_of_gates' => 60, 'city_id' => 186, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Shan Ywar Thit BS", 'number_of_gates' => 60, 'city_id' => 187, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hpapun BS", 'number_of_gates' => 60, 'city_id' => 188, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Kamarmaung BS", 'number_of_gates' => 60, 'city_id' => 189, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kawkareik BS", 'number_of_gates' => 60, 'city_id' => 190, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyondoe BS", 'number_of_gates' => 60, 'city_id' => 191, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hpayarthonesu BS", 'number_of_gates' => 60, 'city_id' => 192, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaikdon BS", 'number_of_gates' => 60, 'city_id' => 193, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyainseikgyi BS", 'number_of_gates' => 60, 'city_id' => 194, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myawaddy BS", 'number_of_gates' => 60, 'city_id' => 195, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Su Ka Li BS", 'number_of_gates' => 60, 'city_id' => 196, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Waw Lay Myaing (Waw Lay BS", 'number_of_gates' => 60, 'city_id' => 197, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Baw Ga Li BS", 'number_of_gates' => 60, 'city_id' => 198, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Leik Tho BS", 'number_of_gates' => 60, 'city_id' => 199, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thandaung BS", 'number_of_gates' => 60, 'city_id' => 200, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thandaunggyi BS", 'number_of_gates' => 60, 'city_id' => 201, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Chauk BS", 'number_of_gates' => 60, 'city_id' => 202, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaw BS", 'number_of_gates' => 60, 'city_id' => 203, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kamma BS2", 'number_of_gates' => 60, 'city_id' => 204, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Minbu BS", 'number_of_gates' => 60, 'city_id' => 205, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Saku BS", 'number_of_gates' => 60, 'city_id' => 206, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mindon BS", 'number_of_gates' => 60, 'city_id' => 207, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Minhla BS", 'number_of_gates' => 60, 'city_id' => 208, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Myaing BS", 'number_of_gates' => 60, 'city_id' => 209, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myothit BS1", 'number_of_gates' => 60, 'city_id' => 210, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Natmauk BS", 'number_of_gates' => 60, 'city_id' => 211, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ngape BS", 'number_of_gates' => 60, 'city_id' => 212, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pwintbyu BS", 'number_of_gates' => 60, 'city_id' => 213, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Salin BS", 'number_of_gates' => 60, 'city_id' => 214, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaukhtu BS", 'number_of_gates' => 60, 'city_id' => 215, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Saw BS", 'number_of_gates' => 60, 'city_id' => 216, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Seikphyu BS", 'number_of_gates' => 60, 'city_id' => 217, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Sidoktaya BS", 'number_of_gates' => 60, 'city_id' => 218, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Sinbaungwe BS", 'number_of_gates' => 60, 'city_id' => 219, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thayet BS", 'number_of_gates' => 60, 'city_id' => 220, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tilin BS", 'number_of_gates' => 60, 'city_id' => 221, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yenangyaung BS", 'number_of_gates' => 60, 'city_id' => 222, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Amarapura BS", 'number_of_gates' => 60, 'city_id' => 223, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myitnge BS", 'number_of_gates' => 60, 'city_id' => 224, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aungmyaythazan BS", 'number_of_gates' => 60, 'city_id' => 225, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Chanayethazan BS", 'number_of_gates' => 60, 'city_id' => 226, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Chanmyathazi BS", 'number_of_gates' => 60, 'city_id' => 227, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Madaya BS", 'number_of_gates' => 60, 'city_id' => 228, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Mahaaungmyay BS", 'number_of_gates' => 60, 'city_id' => 229, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mahlaing BS", 'number_of_gates' => 60, 'city_id' => 230, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mogoke BS", 'number_of_gates' => 60, 'city_id' => 231, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myittha BS", 'number_of_gates' => 60, 'city_id' => 232, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ngazun BS", 'number_of_gates' => 60, 'city_id' => 233, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Bagan BS", 'number_of_gates' => 60, 'city_id' => 234, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ngathayauk BS", 'number_of_gates' => 60, 'city_id' => 235, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Patheingyi BS", 'number_of_gates' => 60, 'city_id' => 236, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyigyitagon BS", 'number_of_gates' => 60, 'city_id' => 237, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Singu BS", 'number_of_gates' => 60, 'city_id' => 238, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Sintgaing BS", 'number_of_gates' => 60, 'city_id' => 239, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tada-U BS", 'number_of_gates' => 60, 'city_id' => 240, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Takaung BS", 'number_of_gates' => 60, 'city_id' => 241, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thabeikkyin BS", 'number_of_gates' => 60, 'city_id' => 242, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thazi BS", 'number_of_gates' => 60, 'city_id' => 243, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Wundwin BS", 'number_of_gates' => 60, 'city_id' => 244, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Chaungzon BS", 'number_of_gates' => 60, 'city_id' => 245, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaikmaraw BS", 'number_of_gates' => 60, 'city_id' => 246, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaikto BS", 'number_of_gates' => 60, 'city_id' => 247, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kamarwet BS", 'number_of_gates' => 60, 'city_id' => 248, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Mudon BS", 'number_of_gates' => 60, 'city_id' => 249, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Paung BS", 'number_of_gates' => 60, 'city_id' => 250, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Zinkyaik BS", 'number_of_gates' => 60, 'city_id' => 251, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaikkhami BS", 'number_of_gates' => 60, 'city_id' => 252, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thanbyuzayat BS", 'number_of_gates' => 60, 'city_id' => 253, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thaton BS", 'number_of_gates' => 60, 'city_id' => 254, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thuwunnawady BS", 'number_of_gates' => 60, 'city_id' => 255, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Khawzar BS", 'number_of_gates' => 60, 'city_id' => 256, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lamaing BS", 'number_of_gates' => 60, 'city_id' => 257, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ye BS", 'number_of_gates' => 60, 'city_id' => 258, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Det Khi Na Thi Ri BS", 'number_of_gates' => 60, 'city_id' => 259, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Oke Ta Ra Thi Ri BS", 'number_of_gates' => 60, 'city_id' => 260, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Poke Ba Thi R BS", 'number_of_gates' => 60, 'city_id' => 261, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Za Bu Thi Ri BS", 'number_of_gates' => 60, 'city_id' => 262, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Zay Yar Thi Ri BS", 'number_of_gates' => 60, 'city_id' => 263, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ayadaw BS", 'number_of_gates' => 60, 'city_id' => 264, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Banmauk BS", 'number_of_gates' => 60, 'city_id' => 265, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Budalin BS", 'number_of_gates' => 60, 'city_id' => 266, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hkamti BS", 'number_of_gates' => 60, 'city_id' => 267, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Homalin BS", 'number_of_gates' => 60, 'city_id' => 268, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Shwe Pyi Aye BS", 'number_of_gates' => 60, 'city_id' => 269, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Indaw BS", 'number_of_gates' => 60, 'city_id' => 270, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kalewa BS", 'number_of_gates' => 60, 'city_id' => 271, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kanbalu BS", 'number_of_gates' => 60, 'city_id' => 272, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kani BS", 'number_of_gates' => 60, 'city_id' => 273, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Katha BS", 'number_of_gates' => 60, 'city_id' => 274, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kawlin BS", 'number_of_gates' => 60, 'city_id' => 275, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyunhla BS", 'number_of_gates' => 60, 'city_id' => 276, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Htan Par Kway BS", 'number_of_gates' => 60, 'city_id' => 277, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lahe BS", 'number_of_gates' => 60, 'city_id' => 278, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Lay Shi BS", 'number_of_gates' => 60, 'city_id' => 279, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mo Paing Lut BS", 'number_of_gates' => 60, 'city_id' => 280, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Sum Ma Rar BS", 'number_of_gates' => 60, 'city_id' => 281, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mawlaik BS", 'number_of_gates' => 60, 'city_id' => 282, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mingin BS", 'number_of_gates' => 60, 'city_id' => 283, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myaung BS", 'number_of_gates' => 60, 'city_id' => 284, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Don Hee BS", 'number_of_gates' => 60, 'city_id' => 285, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nanyun BS", 'number_of_gates' => 60, 'city_id' => 286, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pansaung BS", 'number_of_gates' => 60, 'city_id' => 287, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pale BS", 'number_of_gates' => 60, 'city_id' => 288, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Paungbyin BS", 'number_of_gates' => 60, 'city_id' => 289, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pinlebu BS", 'number_of_gates' => 60, 'city_id' => 290, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Salingyi BS", 'number_of_gates' => 60, 'city_id' => 291, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyauk Myaung BS", 'number_of_gates' => 60, 'city_id' => 292, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tabayin BS", 'number_of_gates' => 60, 'city_id' => 293, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Khampat BS", 'number_of_gates' => 60, 'city_id' => 294, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myothit BS2", 'number_of_gates' => 60, 'city_id' => 295, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tamu BS", 'number_of_gates' => 60, 'city_id' => 296, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Taze BS", 'number_of_gates' => 60, 'city_id' => 297, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tigyaing BS", 'number_of_gates' => 60, 'city_id' => 298, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Wetlet BS", 'number_of_gates' => 60, 'city_id' => 299, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Wuntho BS", 'number_of_gates' => 60, 'city_id' => 300, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yinmarbin BS", 'number_of_gates' => 60, 'city_id' => 301, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ho Tawng (Ho Tao) BS", 'number_of_gates' => 60, 'city_id' => 302, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mong Hpen BS", 'number_of_gates' => 60, 'city_id' => 303, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mong Kar BS", 'number_of_gates' => 60, 'city_id' => 304, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mong Pawk BS", 'number_of_gates' => 60, 'city_id' => 305, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Monghpyak BS", 'number_of_gates' => 60, 'city_id' => 306, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Monghsat BS", 'number_of_gates' => 60, 'city_id' => 307, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongkhoke BS", 'number_of_gates' => 60, 'city_id' => 308, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Mongkhet BS", 'number_of_gates' => 60, 'city_id' => 309, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongla BS", 'number_of_gates' => 60, 'city_id' => 310, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongping BS", 'number_of_gates' => 60, 'city_id' => 311, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tontar BS", 'number_of_gates' => 60, 'city_id' => 312, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hmone Hta BS", 'number_of_gates' => 60, 'city_id' => 313, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongton BS", 'number_of_gates' => 60, 'city_id' => 314, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ponparkyin BS", 'number_of_gates' => 60, 'city_id' => 315, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongpauk BS", 'number_of_gates' => 60, 'city_id' => 316, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongyang BS", 'number_of_gates' => 60, 'city_id' => 317, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongyawng BS", 'number_of_gates' => 60, 'city_id' => 318, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Mongyu BS", 'number_of_gates' => 60, 'city_id' => 319, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nam Hpai BS", 'number_of_gates' => 60, 'city_id' => 320, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kenglat BS", 'number_of_gates' => 60, 'city_id' => 321, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tarlay BS", 'number_of_gates' => 60, 'city_id' => 322, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Aik Chan (Ai' Chun) BS", 'number_of_gates' => 60, 'city_id' => 323, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hkun Mar (Hkwin Ma) BS", 'number_of_gates' => 60, 'city_id' => 324, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hopang BS", 'number_of_gates' => 60, 'city_id' => 325, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Namtit BS", 'number_of_gates' => 60, 'city_id' => 326, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pan Lon BS", 'number_of_gates' => 60, 'city_id' => 327, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hsawng Hpa (Saun Pha) BS", 'number_of_gates' => 60, 'city_id' => 328, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Hseni BS", 'number_of_gates' => 60, 'city_id' => 329, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hsipaw BS", 'number_of_gates' => 60, 'city_id' => 330, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ka Lawng Hpar BS", 'number_of_gates' => 60, 'city_id' => 331, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mong Maw BS", 'number_of_gates' => 60, 'city_id' => 332, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Konkyan BS", 'number_of_gates' => 60, 'city_id' => 333, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Maw Hteik BS", 'number_of_gates' => 60, 'city_id' => 334, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kunlong BS", 'number_of_gates' => 60, 'city_id' => 335, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kutkai BS", 'number_of_gates' => 60, 'city_id' => 336, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tarmoenye BS", 'number_of_gates' => 60, 'city_id' => 337, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyaukme BS", 'number_of_gates' => 60, 'city_id' => 338, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Monglon BS", 'number_of_gates' => 60, 'city_id' => 339, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongngawt BS", 'number_of_gates' => 60, 'city_id' => 340, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lashio BS", 'number_of_gates' => 60, 'city_id' => 341, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Chinshwehaw BS", 'number_of_gates' => 60, 'city_id' => 342, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Laukkaing BS", 'number_of_gates' => 60, 'city_id' => 343, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lin Haw BS", 'number_of_gates' => 60, 'city_id' => 344, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Long Htan BS", 'number_of_gates' => 60, 'city_id' => 345, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mabein BS", 'number_of_gates' => 60, 'city_id' => 346, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Man Man Hseng BS", 'number_of_gates' => 60, 'city_id' => 347, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Man Tun BS", 'number_of_gates' => 60, 'city_id' => 348, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Manton BS", 'number_of_gates' => 60, 'city_id' => 349, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Matman BS", 'number_of_gates' => 60, 'city_id' => 350, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongmao BS", 'number_of_gates' => 60, 'city_id' => 351, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongmit BS", 'number_of_gates' => 60, 'city_id' => 352, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongyai BS", 'number_of_gates' => 60, 'city_id' => 353, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Manhlyoe (Manhero) BS", 'number_of_gates' => 60, 'city_id' => 354, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Monekoe BS", 'number_of_gates' => 60, 'city_id' => 355, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Muse BS", 'number_of_gates' => 60, 'city_id' => 356, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pang Hseng (Kyu Koke) BS", 'number_of_gates' => 60, 'city_id' => 357, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nam Hkam Wu BS", 'number_of_gates' => 60, 'city_id' => 358, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Nam Tit BS", 'number_of_gates' => 60, 'city_id' => 359, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Namhkan BS", 'number_of_gates' => 60, 'city_id' => 360, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Namhsan BS", 'number_of_gates' => 60, 'city_id' => 361, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Namtu BS", 'number_of_gates' => 60, 'city_id' => 362, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nar Kawng BS", 'number_of_gates' => 60, 'city_id' => 363, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nar Wee (Na Wi) BS", 'number_of_gates' => 60, 'city_id' => 364, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Narphan BS", 'number_of_gates' => 60, 'city_id' => 365, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nawng Hkit BS", 'number_of_gates' => 60, 'city_id' => 366, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Wein Kawn BS", 'number_of_gates' => 60, 'city_id' => 367, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Nawnghkio BS", 'number_of_gates' => 60, 'city_id' => 368, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Pang Hkam BS", 'number_of_gates' => 60, 'city_id' => 369, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pang Yang BS", 'number_of_gates' => 60, 'city_id' => 370, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Man Kan BS", 'number_of_gates' => 60, 'city_id' => 371, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pangsang BS", 'number_of_gates' => 60, 'city_id' => 372, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pangwaun BS", 'number_of_gates' => 60, 'city_id' => 373, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tangyan BS", 'number_of_gates' => 60, 'city_id' => 374, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yawng Lin BS", 'number_of_gates' => 60, 'city_id' => 375, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yin Pang BS", 'number_of_gates' => 60, 'city_id' => 376, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hopong BS", 'number_of_gates' => 60, 'city_id' => 377, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hsihseng BS", 'number_of_gates' => 60, 'city_id' => 378, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Kalaw BS", 'number_of_gates' => 60, 'city_id' => 379, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kar Li BS", 'number_of_gates' => 60, 'city_id' => 380, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kunhing BS", 'number_of_gates' => 60, 'city_id' => 381, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyethi BS", 'number_of_gates' => 60, 'city_id' => 382, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongnawng BS", 'number_of_gates' => 60, 'city_id' => 383, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Laihka BS", 'number_of_gates' => 60, 'city_id' => 384, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Homein BS", 'number_of_gates' => 60, 'city_id' => 385, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Langkho BS", 'number_of_gates' => 60, 'city_id' => 386, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Intaw BS", 'number_of_gates' => 60, 'city_id' => 387, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Lawksawk BS", 'number_of_gates' => 60, 'city_id' => 388, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Loilen BS", 'number_of_gates' => 60, 'city_id' => 389, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pinlon BS", 'number_of_gates' => 60, 'city_id' => 390, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mawkmai BS", 'number_of_gates' => 60, 'city_id' => 391, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Monghsu BS", 'number_of_gates' => 60, 'city_id' => 392, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongsan (Hmonesan) BS", 'number_of_gates' => 60, 'city_id' => 393, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongkaing BS", 'number_of_gates' => 60, 'city_id' => 394, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kengtawng BS", 'number_of_gates' => 60, 'city_id' => 395, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongnai BS", 'number_of_gates' => 60, 'city_id' => 396, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Mongpan BS", 'number_of_gates' => 60, 'city_id' => 397, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kho Lam BS", 'number_of_gates' => 60, 'city_id' => 398, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Nansang BS", 'number_of_gates' => 60, 'city_id' => 399, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pekon BS", 'number_of_gates' => 60, 'city_id' => 400, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pindaya BS", 'number_of_gates' => 60, 'city_id' => 401, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Naungtayar BS", 'number_of_gates' => 60, 'city_id' => 402, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pinlaung BS", 'number_of_gates' => 60, 'city_id' => 403, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ayetharyar BS", 'number_of_gates' => 60, 'city_id' => 404, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyauktalonegyi BS", 'number_of_gates' => 60, 'city_id' => 405, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Shwenyaung BS", 'number_of_gates' => 60, 'city_id' => 406, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ywangan BS", 'number_of_gates' => 60, 'city_id' => 407, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Bokpyin BS", 'number_of_gates' => 60, 'city_id' => 408, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Karathuri BS", 'number_of_gates' => 60, 'city_id' => 409, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pyigyimandaing BS", 'number_of_gates' => 60, 'city_id' => 410, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Dawei BS", 'number_of_gates' => 60, 'city_id' => 411, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myitta BS", 'number_of_gates' => 60, 'city_id' => 412, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kawthoung BS", 'number_of_gates' => 60, 'city_id' => 413, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Khamaukgyi BS", 'number_of_gates' => 60, 'city_id' => 414, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyunsu BS", 'number_of_gates' => 60, 'city_id' => 415, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Launglon BS", 'number_of_gates' => 60, 'city_id' => 416, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Myeik BS", 'number_of_gates' => 60, 'city_id' => 417, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Pala BS", 'number_of_gates' => 60, 'city_id' => 418, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Palauk BS", 'number_of_gates' => 60, 'city_id' => 419, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Palaw BS", 'number_of_gates' => 60, 'city_id' => 420, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tanintharyi BS", 'number_of_gates' => 60, 'city_id' => 421, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Thayetchaung BS", 'number_of_gates' => 60, 'city_id' => 422, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kaleinaung BS", 'number_of_gates' => 60, 'city_id' => 423, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Yebyu BS", 'number_of_gates' => 60, 'city_id' => 424, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Cocokyun BS", 'number_of_gates' => 60, 'city_id' => 425, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Dala BS", 'number_of_gates' => 60, 'city_id' => 426, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hlegu BS", 'number_of_gates' => 60, 'city_id' => 427, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Hmawbi BS", 'number_of_gates' => 60, 'city_id' => 428, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ['name' => "Kawhmu BS", 'number_of_gates' => 60, 'city_id' => 429, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kayan BS", 'number_of_gates' => 60, 'city_id' => 430, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kungyangon BS", 'number_of_gates' => 60, 'city_id' => 431, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Kyauktan BS", 'number_of_gates' => 60, 'city_id' => 432, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Tadar BS", 'number_of_gates' => 60, 'city_id' => 433, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Htaukkyant BS", 'number_of_gates' => 60, 'city_id' => 434, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "ဆိပ်ကြီးခနောင်တို BS", 'number_of_gates' => 60, 'city_id' => 435, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Ahpyauk BS", 'number_of_gates' => 60, 'city_id' => 436, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Okekan BS", 'number_of_gates' => 60, 'city_id' => 437, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Taikkyi BS", 'number_of_gates' => 60, 'city_id' => 438, 'zone_id' => 3, 'delivery_rate' => 2000],
    
    ['name' => "Thongwa BS", 'number_of_gates' => 60, 'city_id' => 439, 'zone_id' => 3, 'delivery_rate' => 2000],
    ['name' => "Twantay BS", 'number_of_gates' => 60, 'city_id' => 440, 'zone_id' => 3, 'delivery_rate' => 2000],
       
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // BusStation::truncate();
        // DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        Schema::disableForeignKeyConstraints();
        foreach ($this->bus_stations as $station) {
            $zones = City::find($station["city_id"])->zones;
            $zone_id = $zones->count() > 0 ? $zones['0'] : 1;
            factory(BusStation::class)->create([
                'name' => $station["name"],
                'number_of_gates' => $station["number_of_gates"],
                'city_id' => $station["city_id"],
                'zone_id' => $zone_id,
                'delivery_rate' => $station["delivery_rate"]
            ]);
        }
        Schema::enableForeignKeyConstraints();
    }
}
