<?php

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    protected $cities = [
        ['name' => 'Danubyu', 'name_mm' => 'ဓနုဖြူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Hinthada', 'name_mm' => 'ဟင်္သာတ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Kyonpyaw', 'name_mm' => 'ကျုံပျော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Pathein', 'name_mm' => 'ပုသိမ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Bago', 'name_mm' => 'ပဲခူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Penwegon', 'name_mm' => 'ပဲနွယ်ကုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Nyaunglebin', 'name_mm' => 'ညောင်လေးပင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Oktwin', 'name_mm' => 'အုတ်တွင်း', 'is_collect_only' => 1, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kanyutkwin', 'name_mm' => 'ကညွတ်ကွင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Zayyawadi', 'name_mm' => 'ဇေယျ၀တီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        
        ['name' => 'Taungoo', 'name_mm' => 'တောင်ငူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Thar Ga Ra', 'name_mm' => 'သာဂရ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Waw', 'name_mm' => 'ဝေါ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Hswar', 'name_mm' => 'ဆွာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Yae Ni', 'name_mm' => 'ရေနီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Yedashe', 'name_mm' => 'ရေတာရှည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Letpadan', 'name_mm' => 'လက်ပံတန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Minhla(Bago)', 'name_mm' => 'မင်းလှ(ပဲခူး)', 'is_collect_only' => 1, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nattalin', 'name_mm' => 'နတ်တလင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Oe Thei Kone', 'name_mm' => 'အိုးသည်ကုန်း', 'is_collect_only' => 1, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Paungde', 'name_mm' => 'ပေါင်းတည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Pyay', 'name_mm' => 'ပြည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Thonse', 'name_mm' => 'သုံးဆယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Hpa-An', 'name_mm' => 'ဘားအံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Aunglan', 'name_mm' => 'အောင်လံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Gangaw', 'name_mm' => 'ဂန့်ဂေါ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Magway', 'name_mm' => 'မကွေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Kamma (Pakoku)', 'name_mm' => 'ကမ္မ(ပခုက္ကူ)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Pakokku', 'name_mm' => 'ပခုက္ကူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Pauk', 'name_mm' => 'ပေါက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        
        ['name' => 'Sinphyukyun', 'name_mm' => 'ဆင်ဖြူကျွန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Taungdwingyi', 'name_mm' => 'တောင်တွင်းကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Myit Chay', 'name_mm' => 'မြစ်ခြေ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Yesagyo', 'name_mm' => 'ရေစကြို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Mandalay', 'name_mm' => 'မန္တလေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Kyaukpadaung', 'name_mm' => 'ကျောက်ပန်းတောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Kyaukse', 'name_mm' => 'ကျောက်ဆည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Meiktila', 'name_mm' => 'မိတ္ထီလာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Myingyan', 'name_mm' => 'မြင်းခြံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Natogyi', 'name_mm' => 'နွားထိုးကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        
        ['name' => 'Nyaung-U', 'name_mm' => 'ညောင်ဦး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pyawbwe', 'name_mm' => 'ပျော်ဘွယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Pyinoolwin', 'name_mm' => 'ပြင်ဦးလွင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Taungtha', 'name_mm' => 'တောင်သာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Yamethin', 'name_mm' => 'ရမည်းသင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Bilin', 'name_mm' => 'ဘီးလင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Mawlamyine', 'name_mm' => 'မော်လမြိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Lewe', 'name_mm' => 'လယ်ဝေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Pyinmana', 'name_mm' => 'ပျဉ်းမနား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Tatkon', 'name_mm' => 'တပ်ကုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        
        ['name' => 'Nay Pyi Taw', 'name_mm' => 'နေပြည်တော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Thar Wut Hti', 'name_mm' => 'သာဝတ္တိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Chaung-U', 'name_mm' => 'ချောင်းဦး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Kale', 'name_mm' => 'ကလေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Khin-U', 'name_mm' => 'ခင်ဦး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Monywa', 'name_mm' => 'မုံရွာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Myinmu', 'name_mm' => 'မြင်းမူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Sagaing', 'name_mm' => 'စစ်ကိုင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Shwebo', 'name_mm' => 'ရွှေဘို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Ye-U', 'name_mm' => 'ရေဦး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        
        ['name' => 'Kengtung', 'name_mm' => 'ကျိုင်းတုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Tachileik', 'name_mm' => 'တာချီလိတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Aungpan', 'name_mm' => 'အောင်ပန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Nyaungshwe', 'name_mm' => 'ညောင်ရွှေ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Taunggyi', 'name_mm' => 'တောင်ကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Yangon', 'name_mm' => 'ရန်ကုန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Thanlyin', 'name_mm' => 'သန်လျင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Sittwe', 'name_mm' => 'စစ်​တွေ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 1],
        ['name' => 'Bogale', 'name_mm' => 'ဘိုကလေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Dedaye', 'name_mm' => 'ဒေးဒရဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Einme', 'name_mm' => 'အိမ္မဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Htoogyi', 'name_mm' => 'ထူးကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ingapu', 'name_mm' => 'အင်္ဂပူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kangyidaunt', 'name_mm' => 'ကန်ကြီးထောင့်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaiklat', 'name_mm' => 'ကျိုက်လတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Batye', 'name_mm' => 'ဘက်ရဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyangin', 'name_mm' => 'ကြံခင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaunggon', 'name_mm' => 'ကျောင်းကုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ahtaung', 'name_mm' => 'အထောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Labutta', 'name_mm' => 'လပွတ္တာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'လပွတ္တာ (၃) မိုင်', 'name_mm' => 'လပွတ္တာ (၃) မိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pyinsalu', 'name_mm' => 'ပြင်စလူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Lemyethna', 'name_mm' => 'လေးမျက်နှာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Maubin', 'name_mm' => 'မအူပင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mawlamyinegyun', 'name_mm' => 'မော်လမြိုင်ကျွန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kanaung', 'name_mm' => 'ကနောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myanaung', 'name_mm' => 'မြန်အောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myaungmya', 'name_mm' => 'မြောင်းမြ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hainggyikyun', 'name_mm' => 'ဟိုင်းကြီးကျွန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ngapudaw', 'name_mm' => 'ငပုတော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Ngayokekaung', 'name_mm' => 'ငရုတ်ကောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nyaungdon', 'name_mm' => 'ညောင်တုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pantanaw', 'name_mm' => 'ပန်းတနော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ngwesaung', 'name_mm' => 'ငွေဆောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shwethaungyan', 'name_mm' => 'ရွှေသောင်ယံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ahmar', 'name_mm' => 'အမာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pyapon', 'name_mm' => 'ဖျာပုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thabaung', 'name_mm' => 'သာပေါင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyonmangae', 'name_mm' => 'ကျုံမငေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Wakema', 'name_mm' => 'ဝါးခယ်မ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Ahthoke', 'name_mm' => 'အသုတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ngathaingchaung', 'name_mm' => 'ငသိုင်းချောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Yegyi', 'name_mm' => 'ရေကြည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Zalun', 'name_mm' => 'ဇလွန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hpayargyi', 'name_mm' => 'ဘုရားကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Inntakaw', 'name_mm' => 'အင်းတကော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Daik-U', 'name_mm' => 'ဒိုက်ဦး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Htantabin', 'name_mm' => 'ထန်းတပင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kawa', 'name_mm' => 'ကဝ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thetkala', 'name_mm' => 'သက္ကလ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Kyaukkyi', 'name_mm' => 'ကျောက်ကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyauktaga', 'name_mm' => 'ကျောက်တံခါး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Madauk', 'name_mm' => 'မဒေါက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Peinzalok', 'name_mm' => 'ပိန်းဇလုတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pyuntasa', 'name_mm' => 'ပြွန်တန်ဆာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Phyu', 'name_mm' => 'ဖြူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shwegyin', 'name_mm' => 'ရွှေကျင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kaytumati', 'name_mm' => 'ကေတုမတီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thanatpin', 'name_mm' => 'သနပ်ပင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myo Hla', 'name_mm' => 'မြို့လှ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Gyobingauk', 'name_mm' => 'ကြို့ပင်ကောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Monyo', 'name_mm' => 'မိုးညို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Okpho', 'name_mm' => 'အုတ်ဖို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Oakshitpin', 'name_mm' => 'ဥရှစ်ပင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Padaung', 'name_mm' => 'ပန်းတောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Paukkhaung', 'name_mm' => 'ပေါက်ခေါင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Paungdale', 'name_mm' => 'ပေါင်းတလည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shwedaung', 'name_mm' => 'ရွှေတောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thayarwady', 'name_mm' => 'သာယာဝတီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Inn Ma', 'name_mm' => 'အင်းမ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Puteekone', 'name_mm' => 'ပုတီးကုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thegon', 'name_mm' => 'သဲကုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Zigon', 'name_mm' => 'ဇီးကုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Falam', 'name_mm' => 'ဖလမ်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Rihkhawdar', 'name_mm' => 'ရိခေါ်ဒါရ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hakha', 'name_mm' => 'ဟားခါး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kanpetlet', 'name_mm' => 'ကန်ပက်လက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Matupi', 'name_mm' => 'မတူပီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Rezua', 'name_mm' => 'ရေဇွာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mindat', 'name_mm' => 'မင်းတပ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Paletwa', 'name_mm' => 'ပလက်ဝ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Samee', 'name_mm' => 'ဆမီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tedim', 'name_mm' => 'တီးတိန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thantlang', 'name_mm' => 'ထန်တလန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Cikha', 'name_mm' => 'ကျီခါး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tonzang', 'name_mm' => 'တွန်းဇံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Bhamo', 'name_mm' => 'ဗန်းမော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Chipwi', 'name_mm' => 'ချီဖွေ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pang War', 'name_mm' => 'ပန်ဝါ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hpakant', 'name_mm' => 'ဖားကန့်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Kamaing', 'name_mm' => 'ကာမိုင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Injangyang', 'name_mm' => 'အင်ဂျန်းယန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Khaunglanhpu', 'name_mm' => 'ခေါင်လန်ဖူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Machanbaw', 'name_mm' => 'မချမ်းဘော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mansi', 'name_mm' => 'မံစီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mogaung', 'name_mm' => 'မိုးကောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nammatee', 'name_mm' => 'နမ္မတီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hopin', 'name_mm' => 'ဟိုပင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mohnyin', 'name_mm' => 'မိုးညှင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Dawthponeyan', 'name_mm' => 'ဒေါ့ဖုန်းယန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Lwegel', 'name_mm' => 'လွယ်ဂျယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Momauk', 'name_mm' => 'မိုးမောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myitkyina', 'name_mm' => 'မြစ်ကြီးနား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Sinbo', 'name_mm' => 'ဆင်ဘို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nawngmun', 'name_mm' => 'နောင်မွန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pannandin', 'name_mm' => 'ပန်နန်းဒင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Puta-O', 'name_mm' => 'ပူတာအို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myo Hla1', 'name_mm' => 'မြို့လှ1', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shwegu', 'name_mm' => 'ရွှေကူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Sumprabum', 'name_mm' => 'ဆွမ်ပရာဘွမ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Shin Bway Yang', 'name_mm' => 'ရှင်ဗွေယန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tanai', 'name_mm' => 'တနိုင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tsawlaw', 'name_mm' => 'ဆော့လော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kan Paik Ti', 'name_mm' => 'ကန်ပိုက်တီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Sadung', 'name_mm' => 'ဆဒုံး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Waingmaw', 'name_mm' => 'ဝိုင်းမော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Bawlake', 'name_mm' => 'ဘောလခဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ywarthit', 'name_mm' => 'ရွာသစ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Demoso', 'name_mm' => 'ဒီမောဆို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hpasawng', 'name_mm' => 'ဖါဆောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Hpruso', 'name_mm' => 'ဖရူဆို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Loikaw', 'name_mm' => 'လွိုင်ကော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mese', 'name_mm' => 'မယ်စဲ့', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shadaw', 'name_mm' => 'ရှားတော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hlaingbwe', 'name_mm' => 'လှိုင်းဘွဲ့', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Paingkyon', 'name_mm' => 'ပိုင်ကျုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shan Ywar Thit', 'name_mm' => 'ရှမ်းရွာသစ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hpapun', 'name_mm' => 'ဖာပွန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kamarmaung', 'name_mm' => 'ကမမောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kawkareik', 'name_mm' => 'ကော့ကရိတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Kyondoe', 'name_mm' => 'ကျုံဒိုး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hpayarthonesu', 'name_mm' => 'ဘုရားသုံးဆူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaikdon', 'name_mm' => 'ကျိုက်ဒုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyainseikgyi', 'name_mm' => 'ကြာအင်းဆိပ်ကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myawaddy', 'name_mm' => 'မြဝတီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Su Ka Li', 'name_mm' => 'စုကလိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Waw Lay Myaing (Waw Lay', 'name_mm' => '​ဝေါလေမြိုင် (ဝေါလေ)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Baw Ga Li', 'name_mm' => 'ဘောဂလိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Leik Tho', 'name_mm' => 'လိပ်သို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thandaung', 'name_mm' => 'သံတောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Thandaunggyi', 'name_mm' => 'သံတောင်ကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Chauk', 'name_mm' => 'ချောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaw', 'name_mm' => 'ကျော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kamma MaGway', 'name_mm' => 'ကံမ(မကွေး)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Minbu', 'name_mm' => 'မင်းဘူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Saku', 'name_mm' => 'စကု', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mindon', 'name_mm' => 'မင်းတုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Minhla', 'name_mm' => 'မင်းလှ(မကွေး)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myaing', 'name_mm' => 'မြိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myothit (MaGway)', 'name_mm' => 'မြို့သစ်(မကွေး)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Natmauk', 'name_mm' => 'နတ်မောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ngape', 'name_mm' => 'ငဖဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pwintbyu', 'name_mm' => 'ပွင့်ဖြူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Salin', 'name_mm' => 'စလင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaukhtu', 'name_mm' => 'ကျောက်ထု', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Saw', 'name_mm' => 'ဆော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Seikphyu', 'name_mm' => 'ဆိပ်ဖြူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Sidoktaya', 'name_mm' => 'စေတုတ္တရာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Sinbaungwe', 'name_mm' => 'ဆင်ပေါင်ဝဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thayet', 'name_mm' => 'သရက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Tilin', 'name_mm' => 'ထီးလင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Yenangyaung', 'name_mm' => 'ရေနံချောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Amarapura', 'name_mm' => 'အမရပူရ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myitnge', 'name_mm' => 'မြစ်ငယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Aungmyaythazan', 'name_mm' => 'အောင်မြေသာဇံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Chanayethazan', 'name_mm' => 'ချမ်းအေးသာဇံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Chanmyathazi', 'name_mm' => 'ချမ်းမြသာစည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Madaya', 'name_mm' => 'မတ္တရာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mahaaungmyay', 'name_mm' => 'မဟာအောင်မြေ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mahlaing', 'name_mm' => 'မလှိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Mogoke', 'name_mm' => 'မိုးကုတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myittha', 'name_mm' => 'မြစ်သား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ngazun', 'name_mm' => 'ငါန်းဇွန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Bagan', 'name_mm' => 'ပုဂံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ngathayauk', 'name_mm' => 'ငါ့သရောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Patheingyi', 'name_mm' => 'ပုသိမ်ကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pyigyitagon', 'name_mm' => 'ပြည်ကြီးတံခွန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Singu', 'name_mm' => 'စဉ့်ကူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Sintgaing', 'name_mm' => 'စဉ့်ကိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tada-U', 'name_mm' => 'တံတားဦး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Takaung', 'name_mm' => 'တကောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thabeikkyin', 'name_mm' => 'သပိတ်ကျဉ်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thazi', 'name_mm' => 'သာစည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Wundwin', 'name_mm' => 'ဝမ်းတွင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Chaungzon', 'name_mm' => 'ချောင်းဆုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaikmaraw', 'name_mm' => 'ကျိုက်မရော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaikto', 'name_mm' => 'ကျိုက်ထို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kamarwet', 'name_mm' => 'ကမာ၀က်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mudon', 'name_mm' => 'မုဒုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Paung', 'name_mm' => 'ပေါင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Zinkyaik', 'name_mm' => 'ဇင်းကျိုက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaikkhami', 'name_mm' => 'ကျိုက္ခမီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thanbyuzayat', 'name_mm' => 'သံဖြူဇရပ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thaton', 'name_mm' => 'သထုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thuwunnawady', 'name_mm' => 'သုဝဏ္ဏဝတီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Khawzar', 'name_mm' => 'ခေါဇာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Lamaing', 'name_mm' => 'လမိုင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ye', 'name_mm' => 'ရေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Det Khi Na Thi Ri', 'name_mm' => 'ဒက္ခိဏသီရိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Oke Ta Ra Thi Ri', 'name_mm' => 'ဥတ္တရသီရိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Poke Ba Thi R', 'name_mm' => 'ပုဗ္ဗသီရိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Za Bu Thi Ri', 'name_mm' => 'ဇမ္ဗူသီရိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Zay Yar Thi Ri', 'name_mm' => 'ဇေယျာသီရိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ayadaw', 'name_mm' => 'အရာတော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Banmauk', 'name_mm' => 'ဗန်းမောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Budalin', 'name_mm' => 'ဘုတလင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hkamti', 'name_mm' => 'ခန္တီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Homalin', 'name_mm' => 'ဟုမ္မလင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shwe Pyi Aye', 'name_mm' => 'ရွှေပြည်အေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Indaw', 'name_mm' => 'အင်းတော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Kalewa', 'name_mm' => 'ကလေးဝ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kanbalu', 'name_mm' => 'ကန့်ဘလူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kani', 'name_mm' => 'ကနီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Katha', 'name_mm' => 'ကသာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kawlin', 'name_mm' => 'ကောလင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyunhla', 'name_mm' => 'ကျွန်းလှ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Htan Par Kway', 'name_mm' => 'ထန်ပါခွေ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Lahe', 'name_mm' => 'လဟယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Lay Shi', 'name_mm' => 'လေရှီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mo Paing Lut', 'name_mm' => 'မိုပိုင်းလွတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Sum Ma Rar', 'name_mm' => 'ဆွမ္မရာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mawlaik', 'name_mm' => 'မော်လိုက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mingin', 'name_mm' => 'မင်းကင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myaung', 'name_mm' => 'မြောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Don Hee', 'name_mm' => 'ဒုံဟီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nanyun', 'name_mm' => 'နန်းယွန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pansaung', 'name_mm' => 'ပန်ဆောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pale', 'name_mm' => 'ပုလဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Paungbyin', 'name_mm' => 'ဖေါင်းပြင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pinlebu', 'name_mm' => 'ပင်လည်ဘူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Salingyi', 'name_mm' => 'ဆားလင်းကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyauk Myaung', 'name_mm' => '​ကျောက်မြောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tabayin', 'name_mm' => 'ဒီပဲယင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Khampat', 'name_mm' => 'ခန်းပါတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myothit (Sagaing)', 'name_mm' => 'မြို့သစ်(စစ်ကိုင်း)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tamu', 'name_mm' => 'တမူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Taze', 'name_mm' => 'တန့်ဆည်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tigyaing', 'name_mm' => 'ထီးချိုင့်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Wetlet', 'name_mm' => 'ဝက်လက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Wuntho', 'name_mm' => 'ဝန်းသို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Yinmarbin', 'name_mm' => 'ယင်းမာပင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ho Tawng (Ho Tao)', 'name_mm' => 'ဟိုတောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mong Hpen', 'name_mm' => 'မိုင်းဖျန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mong Kar', 'name_mm' => 'မိုင်းကာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mong Pawk', 'name_mm' => 'မိုင်းပေါက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Monghpyak', 'name_mm' => 'မိုင်းဖြတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Monghsat', 'name_mm' => 'မိုင်းဆတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongkhoke', 'name_mm' => 'မိုင်းခုတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongkhet', 'name_mm' => 'မိုင်းခတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongla', 'name_mm' => 'မိုင်းလား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Mongping', 'name_mm' => 'မိုင်းပြင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tontar', 'name_mm' => 'တုံတာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hmone Hta', 'name_mm' => 'မုံးထ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongton', 'name_mm' => 'မိုင်းတုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ponparkyin', 'name_mm' => 'ပုံပါကျင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongpauk', 'name_mm' => 'မိုင်းပေါက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongyang', 'name_mm' => 'မိုင်းယန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongyawng', 'name_mm' => 'မိုင်းယောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongyu', 'name_mm' => 'မိုင်းယု', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nam Hpai', 'name_mm' => 'နမ့်ဖိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Kenglat', 'name_mm' => 'ကျိုင်းလပ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tarlay', 'name_mm' => 'တာလေ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Aik Chan (Ai Chun)', 'name_mm' => 'အိုက်ချန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hkun Mar (Hkwin Ma)', 'name_mm' => 'ခွန်းမား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hopang', 'name_mm' => 'ဟိုပန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Namtit', 'name_mm' => 'နမ့်တစ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pan Lon', 'name_mm' => 'ပန်လုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hsawng Hpa (Saun Pha)', 'name_mm' => 'ဆောင်ဖ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hseni', 'name_mm' => 'သိန္နီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hsipaw', 'name_mm' => 'သီပေါ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Ka Lawng Hpar', 'name_mm' => 'ကလောင်ဖါ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mong Maw', 'name_mm' => 'မိုင်းမော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Konkyan', 'name_mm' => 'ကုန်းကြမ်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Maw Hteik', 'name_mm' => '​မော်ထိုက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kunlong', 'name_mm' => 'ကွမ်းလုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kutkai', 'name_mm' => 'ကွတ်ခိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tarmoenye', 'name_mm' => 'တာမိုးညဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyaukme', 'name_mm' => 'ကျောက်မဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Monglon', 'name_mm' => 'မိုင်းလုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongngawt', 'name_mm' => 'မိုင်းငေါ့', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Lashio', 'name_mm' => 'လားရှိုး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Chinshwehaw', 'name_mm' => 'ချင်းရွှေဟော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Laukkaing', 'name_mm' => 'လောက်ကိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Lin Haw', 'name_mm' => 'လင်ဟော်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Long Htan', 'name_mm' => 'လုံထန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mabein', 'name_mm' => 'မဘိမ်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Man Man Hseng', 'name_mm' => 'မန်မန်ဆိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Man Tun', 'name_mm' => 'မန်တွန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Manton', 'name_mm' => 'မန်တုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Matman', 'name_mm' => 'မက်မန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Mongmao', 'name_mm' => 'မိုင်းမောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongmit', 'name_mm' => 'မိုးမိတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongyai', 'name_mm' => 'မိုင်းရယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Manhlyoe (Manhero)', 'name_mm' => '(မန်ဟျှိုး)မန့်ဟီးရိုး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Monekoe', 'name_mm' => 'မုန်းကိုး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Muse', 'name_mm' => 'မူဆယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pang Hseng (Kyu Koke)', 'name_mm' => 'ပန်ဆိုင်း (ကြူကုတ်)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nam Hkam Wu', 'name_mm' => 'နမ်ခမ်းဝူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nam Tit', 'name_mm' => 'နမ့်တစ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Namhkan', 'name_mm' => 'နမ့်ခမ်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Namhsan', 'name_mm' => 'နမ့်ဆန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Namtu', 'name_mm' => 'နမ္မတူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nar Kawng', 'name_mm' => 'နားကောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nar Wee (Na Wi)', 'name_mm' => 'နာဝီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Narphan', 'name_mm' => 'နားဖန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nawng Hkit', 'name_mm' => 'နောင်ခစ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Wein Kawn', 'name_mm' => 'ဝိန်းကောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nawnghkio', 'name_mm' => 'နောင်ချို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pang Hkam', 'name_mm' => 'ပန်ခမ့်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pang Yang', 'name_mm' => 'ပန်ယန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Man Kan', 'name_mm' => 'မန်ကန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pangsang', 'name_mm' => 'ပန်ဆန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pangwaun', 'name_mm' => 'ပန်ဝိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tangyan', 'name_mm' => 'တန့်ယန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Yawng Lin', 'name_mm' => 'ယောင်လင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Yin Pang', 'name_mm' => 'ရင်ဖန့်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hopong', 'name_mm' => 'ဟိုပုံး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hsihseng', 'name_mm' => 'ဆီဆိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kalaw', 'name_mm' => 'ကလော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kar Li', 'name_mm' => 'ကာလိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Kunhing', 'name_mm' => 'ကွန်ဟိန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyethi', 'name_mm' => 'ကျေးသီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongnawng', 'name_mm' => 'မိုင်းနောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Laihka', 'name_mm' => 'လဲချား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Homein', 'name_mm' => 'ဟိုမိန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Langkho', 'name_mm' => 'လင်းခေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Intaw', 'name_mm' => 'အင်တော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Lawksawk', 'name_mm' => 'ရပ်စောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Loilen', 'name_mm' => 'လွိုင်လင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pinlon', 'name_mm' => 'ပင်လုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Mawkmai', 'name_mm' => 'မောက်မယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Monghsu', 'name_mm' => 'မိုင်းရှူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongsan (Hmonesan)', 'name_mm' => 'မိုင်းစံ (မုန်းဆန်း)', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongkaing', 'name_mm' => 'မိုင်းကိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kengtawng', 'name_mm' => 'ကျိုင်းတောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongnai', 'name_mm' => 'မိုးနဲ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Mongpan', 'name_mm' => 'မိုင်းပန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kho Lam', 'name_mm' => 'ခိုလမ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Nansang', 'name_mm' => 'နမ့်စန်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pekon', 'name_mm' => 'ဖယ်ခုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Pindaya', 'name_mm' => 'ပင်းတယ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Naungtayar', 'name_mm' => 'နောင်တရား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pinlaung', 'name_mm' => 'ပင်လောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ayetharyar', 'name_mm' => 'အေးသာယာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyauktalonegyi', 'name_mm' => 'ကျောက်တလုံးကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Shwenyaung', 'name_mm' => 'ရွှေညောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ywangan', 'name_mm' => 'ရွာငံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Bokpyin', 'name_mm' => 'ဘုတ်ပြင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Karathuri', 'name_mm' => 'ကရသူရိ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pyigyimandaing', 'name_mm' => 'ပြည်ကြီးမဏ္ဍိုင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Dawei', 'name_mm' => 'ထားဝယ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myitta', 'name_mm' => 'မေတ္တာ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kawthoung', 'name_mm' => 'ကော့သောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Khamaukgyi', 'name_mm' => 'ခမောက်ကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyunsu', 'name_mm' => 'ကျွန်းစု', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Launglon', 'name_mm' => 'လောင်းလုံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Myeik', 'name_mm' => 'မြိတ်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Pala', 'name_mm' => 'ပလ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Palauk', 'name_mm' => 'ပလောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Palaw', 'name_mm' => 'ပုလော', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Tanintharyi', 'name_mm' => 'တနင်္သာရီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thayetchaung', 'name_mm' => 'သရက်ချောင်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kaleinaung', 'name_mm' => 'ကလိန်အောင်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Yebyu', 'name_mm' => 'ရေဖြူ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Cocokyun', 'name_mm' => 'ကိုးကိုးကျွန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Dala', 'name_mm' => 'ဒလ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hlegu', 'name_mm' => 'လှည်းကူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Hmawbi', 'name_mm' => 'မှော်ဘီ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kawhmu', 'name_mm' => 'ကော့မှူး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kayan', 'name_mm' => 'ခရမ်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        
        ['name' => 'Kungyangon', 'name_mm' => 'ကွမ်းခြံကုန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Kyauktan', 'name_mm' => 'ကျောက်တန်း', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Tadar', 'name_mm' => 'တံတား', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Htaukkyant', 'name_mm' => 'ထောက်ကြန့်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'ဆိပ်ကြီးခနောင်တို', 'name_mm' => 'ဆိပ်ကြီးခနောင်တို', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Ahpyauk', 'name_mm' => 'အဖျောက်', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Okekan', 'name_mm' => 'ဥက္ကံ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Taikkyi', 'name_mm' => 'တိုက်ကြီး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Thongwa', 'name_mm' => 'သုံးခွ', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        ['name' => 'Twantay', 'name_mm' => 'တွံတေး', 'is_collect_only' => 0, 'is_on_demand' => 0, 'is_available_d2d' => 0],
        

    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // City::truncate();
        // DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        Schema::disableForeignKeyConstraints();
        foreach ($this->cities as $city) {
            factory(City::class)->create([
                'name' => $city["name"],
                'name_mm' => $city["name_mm"],
                'is_collect_only' => $city["is_collect_only"],
                'is_on_demand' => $city["is_on_demand"],
                'is_available_d2d' => $city["is_available_d2d"]
            ]);
        }
        Schema::enableForeignKeyConstraints();
        // Schema::disableForeignKeyConstraints();
        // factory(City::class, 60)->create();
        // Schema::enableForeignKeyConstraints();
    }
}
