<?php

use App\Models\Gate;
use Illuminate\Database\Seeder;

class GatesTableSeeder extends Seeder
{
    protected $gates = [
        ['name' => "ရွှေတွင်းကြီး", 'bus_id' => 1, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်လံ-ဒဂုံ", 'bus_id' => 2, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မျိုးဆက်သစ်", 'bus_id' => 3, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အာရှ", 'bus_id' => 4, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "အေးချစ်မြိုင်", 'bus_id' => 5, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "နယူးအောင်ကျော်မိုး", 'bus_id' => 6, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "ဝင်းသစ္စာ", 'bus_id' => 7, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်ဇေယျ", 'bus_id' => 8, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေသလ္လာ", 'bus_id' => 9, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "မြို့သစ်-ဒဂုံ", 'bus_id' => 10, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်နိုင်မန်း", 'bus_id' => 11, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မာန်သစ္စာ", 'bus_id' => 12, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရိုးမသစ္စာ", 'bus_id' => 13, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "ကြံတိုင်းအောင်", 'bus_id' => 14, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "တိုးရတနာ", 'bus_id' => 15, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေပြည်မင်း", 'bus_id' => 16, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရေဦးအောင်ရတနာ", 'bus_id' => 17, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဇေယျာမြိုင်ကြီး", 'bus_id' => 18, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "ရွှေမန်းရတနာ", 'bus_id' => 19, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အေးချမ်းဖြိုး", 'bus_id' => 20, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "နယူးစိန်ဌေးလှိုင်", 'bus_id' => 21, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ပြည့်ဖြိုးအောင်", 'bus_id' => 22, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်သစ္စာ", 'bus_id' => 23, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "မြရတနာ", 'bus_id' => 24, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မိုးကောင်းကင်", 'bus_id' => 25, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "တောင်ပြာတန်း", 'bus_id' => 26, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေကမ္ဘာ", 'bus_id' => 27, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မန်းသစ္စာ", 'bus_id' => 28, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "သိန်းသန်းကုဋေ", 'bus_id' => 29, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ESE", 'bus_id' => 30, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဒို့ညီနောင်", 'bus_id' => 31, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "နယူးမန္တလာထွန်း", 'bus_id' => 32, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "စိန်ကမ္ဘာ", 'bus_id' => 33, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "မဟာ", 'bus_id' => 34, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေစကြ်ာ", 'bus_id' => 35, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မိုးထက်အာကာ", 'bus_id' => 36, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေတောင်ရိုး", 'bus_id' => 37, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "တက်လမ်း", 'bus_id' => 38, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေကျောက်ခဲ", 'bus_id' => 39, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မြတ်မန္တလာထွန်း", 'bus_id' => 40, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေလားရှိုး", 'bus_id' => 41, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်ကျော်မိုး", 'bus_id' => 42, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အကယ်ဒမီ", 'bus_id' => 43, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "လုမ္ဗနီ", 'bus_id' => 44, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေမန္တလာ", 'bus_id' => 45, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "Famous", 'bus_id' => 46, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "မြသရဖူ", 'bus_id' => 47, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "Elite", 'bus_id' => 48, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေမန္တလေး", 'bus_id' => 49, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အန်တီဝင်း", 'bus_id' => 50, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဘုန်းမြတ်ပိုင်", 'bus_id' => 51, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ပုပ္ပါး/ပုဂံ", 'bus_id' => 52, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မန်းရာဇာ", 'bus_id' => 53, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေစကြ်ာ", 'bus_id' => 54, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရိုးရိုးလေး", 'bus_id' => 55, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မန္တလာမင်း", 'bus_id' => 56, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "Highclass", 'bus_id' => 57, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေဖားစည်", 'bus_id' => 58, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဂျူပီတာ", 'bus_id' => 59, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "သာမည", 'bus_id' => 60, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေခြင်္သေ့", 'bus_id' => 61, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အဆွေတော်", 'bus_id' => 62, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေအာကာ", 'bus_id' => 63, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မနောတံခွန်", 'bus_id' => 64, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရိုးမ", 'bus_id' => 65, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "နှင်းချယ်ရီ", 'bus_id' => 66, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဝင်းရတနာ", 'bus_id' => 67, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဝင်းရတနာ", 'bus_id' => 68, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "နေလမင်း", 'bus_id' => 69, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "နယူးအောင်တံခွန်", 'bus_id' => 70, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "တင့်တိုင်းအောင်", 'bus_id' => 71, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရိုးမမန္တလာ", 'bus_id' => 72, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေလွန်းပျံ", 'bus_id' => 73, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 74, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်ရတနာ", 'bus_id' => 75, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ပုလော", 'bus_id' => 76, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "ကော့သောင်း", 'bus_id' => 77, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မြတ်ပြည့်စုံ", 'bus_id' => 78, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "စိန်တလုံး", 'bus_id' => 79, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေကချင်", 'bus_id' => 80, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "လေးဝတီ", 'bus_id' => 81, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "စွမ်း Group", 'bus_id' => 82, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "သိန်းသန်းကျော်", 'bus_id' => 83, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ပြည့်ဝ", 'bus_id' => 84, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်ကျော်ဇော", 'bus_id' => 85, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဇေယျရွှေပြည်", 'bus_id' => 86, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှင်လန်း", 'bus_id' => 87, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ပွင့်သစ်ရတနာ", 'bus_id' => 88, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရောင်နီထွန်း", 'bus_id' => 89, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "သိဒ္ဓိအောင်", 'bus_id' => 90, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "သိန်းသန်းကျော်", 'bus_id' => 91, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရတနာ", 'bus_id' => 92, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "သစ္စာဦး", 'bus_id' => 93, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ကြယ်စင်ဟိန်း", 'bus_id' => 94, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေစင်ရတနာ", 'bus_id' => 95, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေနတ်တောင်", 'bus_id' => 96, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်စိုးမိုး", 'bus_id' => 97, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ကရဝိတ်", 'bus_id' => 98, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "နယူးရွှေလီ", 'bus_id' => 99, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေပုလဲသီ", 'bus_id' => 100, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ဓူဝံ", 'bus_id' => 101, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေမြင်းပျံ", 'bus_id' => 102, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေလီရတနာ", 'bus_id' => 103, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ထက်ဦး", 'bus_id' => 104, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောဇမ္ဗူ", 'bus_id' => 105, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ကနောင်မင်းသား", 'bus_id' => 106, 'bus_station_id' => 1, 'gate_debit' => 0],
        ['name' => "ရဲအောင်လံ", 'bus_id' => 107, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "မင်းထက်သာ", 'bus_id' => 108, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "အောင်ပြည့်စုံ", 'bus_id' => 109, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေပြည်သစ်", 'bus_id' => 110, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "သိန်းသန်းကျော်", 'bus_id' => 91, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရတနာ", 'bus_id' => 92, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "သစ္စာဦး", 'bus_id' => 93, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ကြယ်စင်ဟိန်း", 'bus_id' => 94, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရွှေစင်ရတနာ", 'bus_id' => 95, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရွှေနတ်တောင်", 'bus_id' => 96, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "အောင်စိုးမိုး", 'bus_id' => 97, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ကရဝိတ်", 'bus_id' => 98, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "နယူးရွှေလီ", 'bus_id' => 99, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရွှေပုလဲသီ", 'bus_id' => 100, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ဓူဝံ", 'bus_id' => 101, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရွှေမြင်းပျံ", 'bus_id' => 102, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရွှေလီရတနာ", 'bus_id' => 103, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ထက်ဦး", 'bus_id' => 104, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "အောဇမ္ဗူ", 'bus_id' => 105, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ကနောင်မင်းသား", 'bus_id' => 106, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 1, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 2, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 3, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 4, 'gate_debit' => 0],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 5, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 6, 'gate_debit' => 0],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 9, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 10, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 11, 'gate_debit' => 0],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 12, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 13, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 14, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 111, 'bus_station_id' => 15, 'gate_debit' => 1],
        ['name' => "ထက်ဦး", 'bus_id' => 104, 'bus_station_id' => 4, 'gate_debit' => 1],
        ['name' => "အောဇမ္ဗူ", 'bus_id' => 105, 'bus_station_id' => 4, 'gate_debit' => 1],
        ['name' => "ကနောင်မင်းသား", 'bus_id' => 106, 'bus_station_id' => 4, 'gate_debit' => 0],
        ['name' => "ရဲအောင်လံ", 'bus_id' => 107, 'bus_station_id' => 4, 'gate_debit' => 1],
        ['name' => "မင်းထက်သာ", 'bus_id' => 108, 'bus_station_id' => 4, 'gate_debit' => 0],
        ['name' => "အောင်ပြည့်စုံ", 'bus_id' => 109, 'bus_station_id' => 4, 'gate_debit' => 1],
        ['name' => "ရွှေပြည်သစ်", 'bus_id' => 110, 'bus_station_id' => 4, 'gate_debit' => 1],
        ['name' => "ရွှေလွန်းပျံ", 'bus_id' => 73, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "ရွှေမန်းသူ", 'bus_id' => 74, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "အောင်ရတနာ", 'bus_id' => 75, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "ပုလော", 'bus_id' => 76, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "ကော့သောင်း", 'bus_id' => 77, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "မြတ်ပြည့်စုံ", 'bus_id' => 78, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "စိန်တလုံး", 'bus_id' => 79, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "ရွှေကချင်", 'bus_id' => 80, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "လေးဝတီ", 'bus_id' => 81, 'bus_station_id' => 6, 'gate_debit' => 1],
        ['name' => "စွမ်း Group", 'bus_id' => 82, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "သိန်းသန်းကျော်", 'bus_id' => 83, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "ပြည့်ဝ", 'bus_id' => 84, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "အောင်ကျော်ဇော", 'bus_id' => 85, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "ဇေယျရွှေပြည်", 'bus_id' => 86, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "ရွှင်လန်း", 'bus_id' => 87, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "ပွင့်သစ်ရတနာ", 'bus_id' => 88, 'bus_station_id' => 7, 'gate_debit' => 1],
        ['name' => "ရောင်နီထွန်း", 'bus_id' => 89, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "သိဒ္ဓိအောင်", 'bus_id' => 90, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "သိန်းသန်းကျော်", 'bus_id' => 91, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ရတနာ", 'bus_id' => 92, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "သစ္စာဦး", 'bus_id' => 93, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ကြယ်စင်ဟိန်း", 'bus_id' => 94, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ရွှေစင်ရတနာ", 'bus_id' => 95, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ရွှေနတ်တောင်", 'bus_id' => 96, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "အောင်စိုးမိုး", 'bus_id' => 97, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ကရဝိတ်", 'bus_id' => 98, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "နယူးရွှေလီ", 'bus_id' => 99, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ရွှေပုလဲသီ", 'bus_id' => 100, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ဓူဝံ", 'bus_id' => 101, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ရွှေမြင်းပျံ", 'bus_id' => 102, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ရွှေလီရတနာ", 'bus_id' => 103, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "ထက်ဦး", 'bus_id' => 104, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "အောဇမ္ဗူ", 'bus_id' => 105, 'bus_station_id' => 8, 'gate_debit' => 1],
        ['name' => "Elite", 'bus_id' => 48, 'bus_station_id' => 5, 'gate_debit' => 1],
        ['name' => "ဒို့ညီနောင်", 'bus_id' => 31, 'bus_station_id' => 9, 'gate_debit' => 1],
        ['name' => "နယူးမန္တလာထွန်း", 'bus_id' => 32, 'bus_station_id' => 10, 'gate_debit' => 1],
        ['name' => "စိန်ကမ္ဘာ", 'bus_id' => 33, 'bus_station_id' => 11, 'gate_debit' => 1],
        ['name' => "မဟာ", 'bus_id' => 34, 'bus_station_id' => 12, 'gate_debit' => 1],
        ['name' => "ရွှေစကြ်ာ", 'bus_id' => 35, 'bus_station_id' => 13, 'gate_debit' => 1],
        ['name' => "မိုးထက်အာကာ", 'bus_id' => 36, 'bus_station_id' => 14, 'gate_debit' => 1],
        ['name' => "ရွှေတောင်ရိုး", 'bus_id' => 37, 'bus_station_id' => 15, 'gate_debit' => 1],

    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // Gate::truncate();
        // DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        Schema::disableForeignKeyConstraints();
        foreach ($this->gates as $gate) {
            factory(Gate::class)->create([
                'name' => $gate["name"],
                'bus_id' => $gate["bus_id"],
                'bus_station_id' => $gate["bus_station_id"],
                'gate_debit' => $gate["gate_debit"],
            ]);
        }
        Schema::enableForeignKeyConstraints();

        // Schema::disableForeignKeyConstraints();
        // factory(Gate::class, 60)->create();
        // Schema::enableForeignKeyConstraints();
    }
}
