<?php

use App\Models\City;
use App\Models\Zone;
use Illuminate\Database\Seeder;
use App\Traits\TruncateTableSeeder;

class ZonesTableSeeder extends Seeder
{
    use TruncateTableSeeder;

    protected $zones = [
        ['name' => 'Yangon Marathon', 'name_mm' => 'ရန်ကုန် မာရသွန်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံး', 'is_deliver' => 1],
        ['name' => 'Ahlone', 'name_mm' => 'အလုံ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Bahan', 'name_mm' => 'ဗဟန်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Botahtaung', 'name_mm' => 'ဗိုလ်တထောင်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Cocokyun', 'name_mm' => 'ကိုကိုးကျွန်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Dagon', 'name_mm' => 'ဒဂုံ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Dagon Myothit (North)', 'name_mm' => 'ဒဂုံမြို့သစ်မြောက်ပိုင်း (၂၇ -  ၅၁ ရက်ကွက်)', 'city_id' => 1, 'zone_rate' => 1800, 'zone_agent_rate' => 0, 'note' => 'ပြည်ထောင်စု လမ်းအထိ', 'is_deliver' => 1],
        ['name' => 'Dagon Myothit (East) (114 - 158 ward)', 'name_mm' => 'ဒဂုံမြို့သစ်အရှေ့ပိုင်း (၁၁၄ - ၁၅၈ ရက်ကွက်)', 'city_id' => 1, 'zone_rate' => 1800, 'zone_agent_rate' => 0, 'note' => 'ရန်ကုန်စီးပွားရေးတက္ကသိုလ်', 'is_deliver' => 1],
        ['name' => 'Dagon Myothit (East) (1-15 ward)', 'name_mm' => 'ဒဂုံမြို့သစ်အရှေ့ပိုင်း (၁ - ၁၅ ရက်ကွက်)', 'city_id' => 1, 'zone_rate' => 1800, 'zone_agent_rate' => 0, 'note' => 'ကျန်စစ်သားလမ်းအထိ', 'is_deliver' => 1],
        ['name' => 'Dagon Myothit (East) YarTharGyi', 'name_mm' => 'ဒဂုံမြို့သစ်အရှေ့ပိုင်း (ရွာသာကြီး)', 'city_id' => 1, 'zone_rate' => 1800, 'zone_agent_rate' => 0, 'note' => 'စိတ်ကျန်းမာရေးဆေးရုံကြီး နဲ့ လေးထောင့်ကန်သံလမ်း', 'is_deliver' => 1],
        ['name' => 'Dagon Myothit (Seikkan)', 'name_mm' => 'ဒဂုံမြို့သစ်ဆိပ်ကမ်း', 'city_id' => 1, 'zone_rate' => 1800, 'zone_agent_rate' => 0, 'note' => 'သစ်ဆိပ် နှင့် ၂၂ ရက်ကွက်မပို့ပါ', 'is_deliver' => 1],
        ['name' => 'Dagon Myothit (South)', 'name_mm' => 'ဒဂုံမြို့သစ်တောင်ပိုင်း', 'city_id' => 1, 'zone_rate' => 1800, 'zone_agent_rate' => 0, 'note' => 'အရှေ့ဒဂုံစက်မှုဇုံ အထိ', 'is_deliver' => 1],
        ['name' => 'Dala', 'name_mm' => 'ဒလ', 'city_id' => 1, 'zone_rate' => 2000, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Dawbon', 'name_mm' => 'ဒေါပုံ', 'city_id' => 1, 'zone_rate' => 2000, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Hlaing', 'name_mm' => 'လှိုင်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Hlaingtharya', 'name_mm' => 'လှိုင်သာယာ', 'city_id' => 1, 'zone_rate' => 800, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Hlegu', 'name_mm' => 'လှည်းကူး', 'city_id' => 1, 'zone_rate' => 800, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Hmawbi', 'name_mm' => 'မှော်ဘီ', 'city_id' => 1, 'zone_rate' => 1300, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Htantabin', 'name_mm' => 'ထန်းတပင်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Insein', 'name_mm' => 'အင်းစိန်', 'city_id' => 1, 'zone_rate' => 300, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Kamaryut', 'name_mm' => 'ကမာရွတ်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Kawhmu', 'name_mm' => 'ကော့မှုး', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Kayan', 'name_mm' => 'ခရမ်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Kungyangon', 'name_mm' => 'ကွမ်းခြံကုန်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Kyauktada', 'name_mm' => 'ကျောက်တံတား', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Kyauktan', 'name_mm' => 'ကျောက်တန်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Kyeemyindaing', 'name_mm' => 'ကြည့်မြင်တိုင်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Lanmadaw', 'name_mm' => 'လမ်းမတော်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Latha', 'name_mm' => 'လသာ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Mayangone', 'name_mm' => 'မရမ်းကုန်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Mingaladon', 'name_mm' => 'မင်္ဂလာဒုံ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Mingalartaungnyunt', 'name_mm' => 'မင်္ဂလာတောင်ညွန့်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'North Okkalapa', 'name_mm' => 'မြောက်ဥက္ကလာပ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Pabedan', 'name_mm' => 'ပန်းပဲတန်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Pazundaung', 'name_mm' => 'ပုဇွန်တောင်', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Sanchaung', 'name_mm' => 'စမ်းချောင်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Seikgyikanaungto', 'name_mm' => 'ဆိပ်ကြီးခနောင်တို', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Seikkan', 'name_mm' => 'ဆိပ်ကမ်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Shwepyithar', 'name_mm' => 'ရွှေပြည်သာ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'South Okkalapa', 'name_mm' => 'တောင်ဥက္ကလာပ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Taikkyi', 'name_mm' => 'တိုက်ကြီး', 'city_id' => 1, 'zone_rate' => 1400, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Tamwe', 'name_mm' => 'တာမွေ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Thaketa', 'name_mm' => 'သာကေတ', 'city_id' => 1, 'zone_rate' => 500, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Thanlyin', 'name_mm' => 'သန်လျှင်', 'city_id' => 1, 'zone_rate' => 300, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Thingangyun', 'name_mm' => 'သင်္ဃန်းကျွန်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Thongwa', 'name_mm' => 'သုံးခွ', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Twantay', 'name_mm' => 'တွံတေး', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 0],
        ['name' => 'Yankin', 'name_mm' => 'ရန်ကင်း', 'city_id' => 1, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Mandalay Marathon', 'name_mm' => 'မန္တလေး မာရသွန်', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံး', 'is_deliver' => 1],
        ['name' => 'Amarapura', 'name_mm' => 'အမရပူရ', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Aungmyethazan ', 'name_mm' => 'အောင်မြေသာဇံ', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Chanayethazan ', 'name_mm' => 'ချမ်းအေးသာဇံ', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Chanmyathazi ', 'name_mm' => 'ချမ်းမြသာစည်', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Maha Aungmye ', 'name_mm' => 'မဟာအောင်မြေ', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Patheingyi ', 'name_mm' => 'ပုသိမ်ကြီး', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Pyigyidagun ', 'name_mm' => 'ပြည်ကြီးတံခွန်', 'city_id' => 29, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Naypyidaw Marathon', 'name_mm' => 'နေပြည်တော် မာရသွန်', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံး', 'is_deliver' => 1],
        ['name' => 'Det Khi Na Thi Ri', 'name_mm' => 'ဒက္ခိဏသီရိ', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Lewe', 'name_mm' => 'လယ်ဝေး', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Oke Ta Ra Thi Ri', 'name_mm' => 'ဥတ္တရသီရိ', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Poke Ba Thi Ri', 'name_mm' => 'ပုဗ္ဗသီရိ', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Pyinmana', 'name_mm' => 'ပျဉ်းမနား', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Tatkon', 'name_mm' => 'တပ်ကုန်း', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Za Bu Thi Ri', 'name_mm' => 'ဇမ္ဗူသီရိ', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Zay Yar Thi Ri', 'name_mm' => 'ဇေယျာသီရိ', 'city_id' => 41, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'မြို့နယ်', 'is_deliver' => 1],
        ['name' => 'Ah Mhu Htan Ward', 'name_mm' => 'အမှုထမ်းရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Aung Chan Thar Ward', 'name_mm' => 'အောင်ချမ်းသာရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Aung Min Ga Lar Ward', 'name_mm' => 'အောင်မင်္ဂလာရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Bago Su Ward', 'name_mm' => 'ပဲခူးစုရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Dahr Gar Ward', 'name_mm' => 'ဒါရ်ဂါရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Htan Pin Kone Ward', 'name_mm' => 'ထန်းပင်ကုန်းရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Haung (East) Ward', 'name_mm' => 'မြို့ဟောင်းအရှေ့ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Haung (Middle) Ward', 'name_mm' => 'မြို့ဟောင်းအလယ်ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Haung (West) Ward', 'name_mm' => 'မြို့ဟောင်းအနောက်ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Ma (North) Ward', 'name_mm' => 'မြို့မမြောက်ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Ma (South) Ward', 'name_mm' => 'မြို့မတောင်ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Thit (East) Ward', 'name_mm' => 'မြို့သစ်အရှေ့ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Thit (Middle) Ward', 'name_mm' => 'မြို့သစ်အလယ်ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Thit (West) Ward', 'name_mm' => 'မြို့သစ်အနောက်ရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Oke Hpo Su Ward', 'name_mm' => 'အုပ်ဖိုစုရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Thauk Taw Kwin Ward', 'name_mm' => 'သောက်တော်ကွင်းရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Yae Nan Ward', 'name_mm' => 'ရေနံရပ်ကွက်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Kyaukkhauk Pagoda', 'name_mm' => 'ကျိုက်ခေါက်စေတီတော်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'အထိမ်းအမှတ်အဆောက်အဦး', 'is_deliver' => 1],
        ['name' => 'Thila War Port', 'name_mm' => 'သီလဝါ ဆိပ်ကိမ်း', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'အထိမ်းအမှတ်အဆောက်အဦး', 'is_deliver' => 1],
        ['name' => 'Thanlyin Refinery', 'name_mm' => 'သန်လျင် ရေနံချက်စက်ရုံ', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'အထိမ်းအမှတ်အဆောက်အဦး', 'is_deliver' => 1],
        ['name' => 'University of East Yangon Thanlyin', 'name_mm' => 'ရန်ကုန် အရှေ့ပိုင်း တက္ကသိုလ်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ကျောင်း/တက္ကသိုလ်', 'is_deliver' => 1],
        ['name' => 'Myanmar Maritime University Thanlyin', 'name_mm' => 'မြန်မာနိုင်ငံရေကြောင်းပညာတက္ကသိုလ်', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ကျောင်း/တက္ကသိုလ်', 'is_deliver' => 1],
        ['name' => 'Technological University Thanlyin', 'name_mm' => 'နည်းပညာတက္ကသိုလ်(သန်လျင်)', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ကျောင်း/တက္ကသိုလ်', 'is_deliver' => 1],
        ['name' => 'Yangon Co-operative University Thanlyin', 'name_mm' => 'သမဝါယမတက္ကသိုလ်(သန်လျင်)', 'city_id' => 2, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ကျောင်း/တက္ကသိုလ်', 'is_deliver' => 1],
        ['name' => 'Ah Lel Ward', 'name_mm' => 'အလယ်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Ah Lone Ward', 'name_mm' => 'အလုံရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Aung Chan Thar Ward1', 'name_mm' => 'အောင်ချမ်းသာရပ်ကွက်1', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Aung Min Ga Lar Ward1', 'name_mm' => 'အောင်မင်္ဂလာရပ်ကွက်1', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Aye Thar Yar Ward', 'name_mm' => 'အေးသာယာရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Chan Mya Thar Zi Ward', 'name_mm' => 'ချမ်းမြသာစည်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Chan Mya Wa Di Ward', 'name_mm' => 'ချမ်းမြဝတီရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Daw Na Chan Ward', 'name_mm' => 'ဒေါနခြံရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Hpa Yar Gyi Ward', 'name_mm' => 'ဘုရားကြီးရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Hpone Soe Ward', 'name_mm' => 'ဖုန်းစိုးရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Htan Taw Ward', 'name_mm' => 'ထန်းတောရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Inn Ywar Thit Ward', 'name_mm' => 'အင်းရွာသစ်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Kwayt Gyi Ward', 'name_mm' => 'ကွေ့ကြီးရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Lel Di Ward', 'name_mm' => 'လယ်တီရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Monywa (South) Ward', 'name_mm' => 'မုံရွာတောင်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Mya Wa Di Ward', 'name_mm' => 'မြဝတီရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Thit Ward', 'name_mm' => 'မြို့သစ်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Nan Da Wun Ward', 'name_mm' => 'နန္ဒဝန်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Nat Lu Hteik Pan Ward', 'name_mm' => 'နတ်လူထိပ်ပန်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Oe Bo (South) Ward', 'name_mm' => 'အိုးဘိုတောင်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Set Hmu Zon Ward', 'name_mm' => 'စက်မှုဇုံရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Sit Pin Ward', 'name_mm' => 'စစ်ပင်ရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Sue Lay Gone Ward', 'name_mm' => 'ဆူးလေကုန်းရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Thar Lar Ward', 'name_mm' => 'သလ္လာရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Ya Da Nar Bon Ward', 'name_mm' => 'ရတနာပုံရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Yan Kin Ward', 'name_mm' => 'ရန်ကင်းရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Yone Gyi Ward', 'name_mm' => 'ရုံးကြီးရပ်ကွက်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Monywa University', 'name_mm' => 'Monywa ကျောင်း/တက္ကသိုလ်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Monywa Education College', 'name_mm' => 'Monywa Edu ကျောင်း/တက္ကသိုလ်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Monywa Institute of Economics', 'name_mm' => 'Monywa Insti ကျောင်း/တက္ကသိုလ်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Technological University, Monywa', 'name_mm' => 'Technological ကျောင်း/တက္ကသိုလ်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Computer University, Monywa ', 'name_mm' => 'Computer ကျောင်း/တက္ကသိုလ်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Thambuddhe Pagoda', 'name_mm' => 'သမ္ဗုဒ္ဓေဘုုရား', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Maha Bodhi Ta Htaung ', 'name_mm' => 'မဟာဗောဓိတထောင်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'The Laykyun Sekkya Buddha', 'name_mm' => 'လေးကျွန်းစင်္ကြာ', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Phowintaung', 'name_mm' => 'ဖိုလ်ဝင်တောင်', 'city_id' => 23, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Chin Thayt U Ward', 'name_mm' => 'ခြင်္သေ့ဦးရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Htee Hlaing Ward', 'name_mm' => 'ထီးလှိုင်ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Kan Taw Ward', 'name_mm' => 'ကန်တော်ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Kyet Ti Ward', 'name_mm' => 'ကြက်တည်ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Lan Ma Kye Ward', 'name_mm' => 'လမ်းမကျယ်ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Man Ward', 'name_mm' => 'မန်းရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Min Gyi Nyo Ward', 'name_mm' => 'မင်းကြီးညိုရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Myo Gyi Ward', 'name_mm' => 'မြို့ကြီးရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Ngwe Hlan Oe Kone Ward', 'name_mm' => 'ငွေလှံအိုးကုန်းရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Oke Kyut Tan (East) Ward', 'name_mm' => 'အုတ်ကျွတ်တန်း(အရှေ.)ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Oke Kyut Tan (South) Ward', 'name_mm' => 'အုတ်ကျွတ်တန်း(တောင်)ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Oke Kyut Tan (West) Ward', 'name_mm' => 'အုတ်ကျွတ်တန်း(အနောက်)ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Pan Be Dan (North) Ward', 'name_mm' => 'ပန်းဘဲတန်း(မြောက်)ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Pan Be Dan (South) Ward', 'name_mm' => 'ပန်းဘဲတန်း(တောင်)ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Rakhine Su /Nay Pu Kone Ward', 'name_mm' => 'ရခိုင်စု/နေပူကုန်းရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Shan Tan Kway Zay Ward', 'name_mm' => 'ရှမ်းတန်းကွေ့ဈေးရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Tat Myay Ward', 'name_mm' => 'တပ်မြေရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Taung Kway Zay Ward', 'name_mm' => 'တောင်ကွေ.ဈေးရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Yoe Da Yar Tan Ward', 'name_mm' => 'ယိုးဒယားတန်းရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Zaung Chan (South) Ward', 'name_mm' => 'ဇောင်ချမ်းတောင်ရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Zay Tan Ward', 'name_mm' => 'ဈေးတန်းရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Zay Ward', 'name_mm' => 'ဈေးရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရုံးလာယူ', 'is_deliver' => 0],
        ['name' => 'Zay Yar Khin U Ward', 'name_mm' => 'ဇေယျာခင်ဦးရပ်ကွက်', 'city_id' => 48, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Khit Ta Yar Ward', 'name_mm' => 'ခေတ္တရာမြို့သစ်ရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Kyaung Gyi Oe Tan Ward', 'name_mm' => 'အိုးတမ်းရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Na Wa Day Ward', 'name_mm' => 'နဝဒေးရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Na Win Ward', 'name_mm' => 'နဝင်းရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Pyi Thar Yar Ward', 'name_mm' => 'ပြည်သာယာရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'San Taw Ward', 'name_mm' => 'ဆံတော်ရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Shwe Ku Ward', 'name_mm' => 'ရွှေကူရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Shwe Ta Gar Ward', 'name_mm' => 'ရွှေတံခါးရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Sin Su Ward', 'name_mm' => 'ဆင်စုရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Ywar Be Ward', 'name_mm' => 'ရွာဘဲရပ်ကွက်', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Tar Kwa', 'name_mm' => 'တာကွ', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'Sael Myaung', 'name_mm' => 'ဆည်မြောင်း', 'city_id' => 9, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (1) Ward', 'name_mm' => 'အမှတ် (၁) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (2) Ward', 'name_mm' => 'အမှတ် (၂) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (3) Ward', 'name_mm' => 'အမှတ် (၃) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (4) Ward', 'name_mm' => 'အမှတ် (၄) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (5) Ward', 'name_mm' => 'အမှတ် (၅) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (6) Ward', 'name_mm' => 'အမှတ် (၆) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (7) Ward', 'name_mm' => 'အမှတ် (၇) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (8) Ward', 'name_mm' => 'အမှတ် (၈) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (9) Ward', 'name_mm' => 'အမှတ် (၉) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (10) Ward', 'name_mm' => 'အမှတ် (၁၀) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (11) Ward', 'name_mm' => 'အမှတ် (၁၁) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (12) Ward', 'name_mm' => 'အမှတ် (၁၂) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (13) Ward', 'name_mm' => 'အမှတ် (၁၃) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (14) Ward', 'name_mm' => 'အမှတ် (၁၄) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (15) Ward', 'name_mm' => 'အမှတ် (၁၅) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (16) Ward', 'name_mm' => 'အမှတ် (၁၆) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (17) Ward', 'name_mm' => 'အမှတ် (၁၇) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (18) Ward', 'name_mm' => 'အမှတ် (၁၈) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (19) Ward', 'name_mm' => 'အမှတ် (၁၉) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (20) Ward', 'name_mm' => 'အမှတ် (၂၀) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'No (21) Ward', 'name_mm' => 'အမှတ် (၂၁) ရပ်ကွက်', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
        ['name' => 'A Nee Sek Kan', 'name_mm' => 'အနီးစခန်း', 'city_id' => 71, 'zone_rate' => 0, 'zone_agent_rate' => 0, 'note' => 'ရပ်ကွက်', 'is_deliver' => 1],
    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->truncate('zones');

        foreach ($this->zones as $zone) {
            factory(Zone::class)->create([
                'name' => $zone["name"],
                'name_mm' => $zone["name_mm"],
                'city_id' => $zone["city_id"],
                'zone_rate' => $zone["zone_rate"],
                'zone_agent_rate' => $zone["zone_agent_rate"],
                'note' => $zone["note"],
                'is_deliver' => $zone["is_deliver"]
            ]);
        }
        // 'city_id' => City::where("name", $zone["city"])->first()


        // factory(Zone::class, 60)->create();
    }
}
